# MkDocs Configuration Reference: https://www.mkdocs.org/user-guide/configuration/
# MkDocs Material:
#   - Setup: https://squidfunk.github.io/mkdocs-material/setup
#   - Plugins: https://squidfunk.github.io/mkdocs-material/plugins/
#   - Reference: https://squidfunk.github.io/mkdocs-material/reference/

# Project information
site_name: MkDocs Material Starter # Sets the main title for the project.
site_url: https://jumumu.github.io # Sets the canonical URL of the site.
site_author: Jumumu                # Sets the name of the author.
site_description: >-               # Sets the site description.
  A starter project for using MkDocs with the Material theme.

# The directory containing the documentation source markdown files (https://www.mkdocs.org/user-guide/configuration/#docs_dir)
docs_dir: docs

# Repository
repo_url: https://github.com/Jumumu/mkdocs-material-starter # When set, provides a link to your repository (GitHub, Bitbucket, GitLab, ...) on each page.
repo_name: Jumumu/mkdocs-material-starter                   # When set, provides the name for the link to your repository on each page.

# Copyright
copyright: Copyright &copy; 2024 Jumumu # Set the copyright information to be included in the documentation by the theme.

# The path from the base repo_url to the docs directory when directly viewing a page (https://www.mkdocs.org/user-guide/configuration/#edit_uri)
edit_uri: edit/main/docs/

# Configuration
theme:
  name: material               # Use the MkDocs material theme
  custom_dir: overrides        # A directory containing HTML source to extend the theme. This will be used to display an announcement at the top of the site.
  features:
    - announce.dismiss         # Allow announcements to be marked as read by the user (https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-header/#mark-as-read)
    - content.action.edit      # Add a button on each page to edit the source Markdown (https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#code-actions)
    - content.action.view      # Add a button on each page to view the source Markdown (https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#code-actions)
    - content.code.copy        # Add a button to copy a code block's content to clipboard (https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-copy-button)
    # - header.autohide        # Automatically hide the header when the user scrolls past a certain threshold, leaving more space for content (https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-header/#automatic-hiding)
    # - navigation.expand      # When expansion is enabled, the left sidebar will expand all collapsible subsections by default, so the user doesn't have to open subsections manually (https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-expansion)
    - navigation.footer        # Adds links to the previous and next page in the footer (https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/#navigation)e
    - navigation.sections      # When sections are enabled, top-level sections are rendered as groups in the sidebar (https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-sections)
    # - navigation.tabs          # When tabs are enabled, top-level sections are rendered in a menu layer below the header (https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-tabs)
    # - navigation.tabs.sticky # When sticky tabs are enabled, navigation tabs will lock below the header and always remain visible when scrolling down (https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#sticky-navigation-tabs)
    - navigation.top           # A back-to-top button can be shown when the user, after scrolling down, starts to scroll up again (https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#back-to-top-button)
    - navigation.tracking      # When anchor tracking is enabled, the URL in the address bar is automatically updated with the active anchor as highlighted in the table of contents (https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#anchor-tracking)
    - search.highlight         # When search highlighting is enabled and a user clicks on a search result, Material for MkDocs will highlight all occurrences after following the link (https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#search-highlighting)
    - search.share             # When search sharing is activated, a share button is rendered next to the reset button, which allows to deep link to the current search query and result (https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#search-sharing)
    - search.suggest           # When search suggestions are enabled, the search will display the likeliest completion for the last word which can be accepted with the Right key (https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#search-suggestions)
    - toc.follow               # When anchor following for the table of contents is enabled, the sidebar is automatically scrolled so that the active anchor is always visible (https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#anchor-following)
  # Sets the color scheme (https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/)
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate   # Sets the site color scheme (https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#color-scheme)
      primary: indigo # Sets the primary color (https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#primary-color)
      accent: indigo  # Sets the accent color (https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#accent-color)
      toggle:
        # Adds a button to toggle to light mode (https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#color-palette-toggle)
        icon: material/weather-sunny
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default # Sets the site color scheme (https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#color-scheme)
      primary: indigo # Sets the primary color (https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#primary-color)
      accent: indigo  # Sets the accent color (https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#accent-color)
      toggle:
        # Adds a button to toggle to dark mode (https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#color-palette-toggle)
        icon: material/weather-night
        name: Switch to dark mode
  # Sets the site font (https://squidfunk.github.io/mkdocs-material/setup/changing-the-fonts/)
  font:
    text: Roboto
    code: Roboto Mono
  # logo: assets/logo.png # Sets a custom logo (https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/)
  icon:
    repo: fontawesome/brands/github # Sets a custom repository icon for the repository link on each page (https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#repository-icon)

# Additional configuration
extra:
  # Adds social media links to the bottom-right of the footer on the site (https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/?h=social#social-links)
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Jumumu
    - icon: fontawesome/brands/twitch
      link: https://www.twitch.tv/jumumu
#     - icon: fontawesome/brands/python
#       link: https://pypi.org/project/mkdocs-material/
#     - icon: fontawesome/brands/mastodon
#       link: https://fosstodon.org/@squidfunk
#     - icon: fontawesome/brands/youtube
#       link: https://twitter.com/squidfunk

# Extensions
markdown_extensions:
  # Generate a table of contents on the right side of each page (https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#table-of-contents)
  - toc:
      title: Tables of Contents # Set the title of the table of contents (https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#+toc.title)
      permalink: true           # Adds an anchor link containing the paragraph symbol ¶ or another custom symbol at the end of each headline (https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#+toc.permalink)
      baselevel: 3
  - pymdownx.betterem:          # BetterEm is an extension that aims to improve emphasis (bold and italic) handling (https://facelessuser.github.io/pymdown-extensions/extensions/betterem/)
      smart_enable: all
  - pymdownx.highlight:         # Adds support for syntax highlighting in code blocks (https://facelessuser.github.io/pymdown-extensions/extensions/highlight/)
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite       # Adds support for inline code highlighting (https://facelessuser.github.io/pymdown-extensions/extensions/inlinehilite/)
  - pymdownx.tasklist           # Adds support for GitHub flavored Markdown task lists (https://facelessuser.github.io/pymdown-extensions/extensions/tasklist/)
  - pymdownx.superfences        # Required for code highlighting to work (https://facelessuser.github.io/pymdown-extensions/extensions/superfences/)
